<?php

namespace SCRUM\SwiftairBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CapaciteitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CapaciteitenRepository extends EntityRepository
{
}
