<?php

namespace SCRUM\SwiftairBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CreditRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CreditRepository extends EntityRepository
{
}
