<?php

namespace SCRUM\SwiftairBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LandenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LandenRepository extends EntityRepository
{
}
