<?php

namespace SCRUM\SwiftairBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VluchtenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VluchtenRepository extends EntityRepository {
    public function vindVlucht($van, $naar) {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT vluchten.id as vlid FROM vluchten, luchthavens, landen WHERE vertrekhavenid = ' . $van . ' AND aankomsthavenid = ' . $naar
            )
            ->getResult();
    }
}
