scrum_swiftair_homepage:
    path:     /admin/hello/{name}
    defaults: { _controller: SCRUMSwiftairBundle:Default:index }
    
scrum_swiftair_index:
    path: /
    defaults: { _controller: SCRUMSwiftairBundle:Index:index }

scrum_swiftair_CRUD:
    resource: "@SCRUMSwiftairBundle/Controller/"
    type: annotation