scrum_swiftair_index:
    path: /
    defaults: { _controller: SCRUMSwiftairBundle:Index:index }

scrum_swiftair_booking:
    path: /booking/{from}/{to}/{class}/{num}
    defaults: { _controller: SCRUMSwiftairBundle:Bestellingen:booking }

scrum_swiftair_about:
    path: /about
    defaults: { _controller: SCRUMSwiftairBundle:About:index }

scrum_swiftair_profile:
    path: /profile
    defaults: { _controller: SCRUMSwiftairBundle:Profile:index }

scrum_swiftair_contact:
    path: /contact
    defaults: { _controller: SCRUMSwiftairBundle:Contact:index }

scrum_swiftair_CRUD:
    resource: "@SCRUMSwiftairBundle/Controller/"
    type: annotation